### PR TITLE
Update image to work with latest version of cron and other improvements

### PR DESCRIPTION
**Pull request by rorist**
Hello,

Particularly f8432f4, 9f1e589 and 79ebbe5 which make the image work again. The other change is an improvement to allow configuration of encryption.

Cheers

### CODE REVIEW

**Comment by VeselaHouba** [comment]
I've missed that #2  is already addressed. Closing #2 now
not sure if @ppadial maintains this repo

**Comment by ppadial** [comment]
Im taking a look from time to time, i will merge that and recreate the image.

Thanks for the work and comments, really appreciate it

**Comment by ppadial** [comment]
Docker container is being built right now 🙊

**Comment by ppadial** [comment]
Done, you can docker pull with confidence.

Also, i will update the documentation in README.md that was not updated in the PR in a new commit.

**Comment by ppadial** [comment]
Done, thanks !

**Pull request merged**
